export const REQUEST_LINKS_PENDING = 'REQUEST_LINKS_PENDING';
export const REQUEST_LINKS_SUCCESS = 'REQUEST_LINKS_SUCCESS';
export const REQUEST_LINKS_FAILED = 'REQUEST_LINKS_FAILED';
export const SELECTED_SHELTER = 'SELECTED_SHELTER';
